---
title: "NBA Playoff Stat Predictions"
name: "Matthew Fenstermaker"
date: "5/23/2024"
output: html_notebook
---

*Note: Date is the when the data is edited. Players have been removed when teams lost, as they can no longer be factored in.*

*Available options for players include Jayson Tatum, Jaylen Brown, Jrue Holiday, Derrick White, Luka Doncic, Kyrie Irving, PJ Washington, Derick Lively, Daniel Gafford, Josh Green, Anthony Edwards, KAT, Jaden McDaniels, Rudy Gobert, and Mike Conley.*

```{r echo = T}
#Read in data and find running average of each category

#Final Average can be found by looking at the last game for each player

library(readxl)
library(dplyr)
nba <- read_excel("NBA DATA.xlsx")
nba <- nba %>%
  slice(-c(141,242,263)) #Removing Missed Games
nba <- na.omit(nba)
nba$Pts <- as.numeric(nba$Pts)
nba$Reb <- as.numeric(nba$Reb)
nba$Assists <- as.numeric(nba$Assists)
nba$`3PM` <- as.numeric(nba$`3PM`)

nba <- nba %>%
  group_by(Player) %>%
  mutate(
    Running_Avg_Pts = cumsum(Pts) / row_number(),
    Running_Avg_Reb = cumsum(Reb) / row_number(),
    Running_Avg_Assists = cumsum(Assists) / row_number(),
    Running_Avg_3PM = cumsum(`3PM`) / row_number()
  )
```

```{r echo = T}
#Create indicators for each player

DW <- nba %>%
  filter(Player == "Derrick White")
LD <- nba %>%
  filter(Player == "Luka Doncic")
AE <- nba %>%
  filter(Player == "Anthony Edwards")
JB <- nba %>%
  filter(Player == "Jaylen Brown")
PJ <- nba %>%
  filter(Player == "PJ Washington")
DL <- nba %>%
  filter(Player == "Dereck Lively")
DG <- nba %>%
  filter(Player == "Daniel Gafford")
MC <- nba %>%
  filter(Player == "Mike Conley")
RG <- nba %>%
  filter(Player == "Rudy Gobert")
JG <- nba %>%
  filter(Player == "Josh Green")
JH <- nba %>%
  filter(Player == "Jrue Holiday")
KT <- nba %>%
  filter(Player == "KAT")
JM <- nba %>%
  filter(Player == "Jaden McDaniels")
JT <- nba %>%
  filter(Player == "Jayson Tatum")
KI <- nba %>%
  filter(Player == "Kyrie Irving")
```

```{r echo = T}
#Show graphical analysis of each player with the respected stat line you wish 

library(ggplot2)
ggplot(KI, aes(x = KI$`Total Game`, y = Assists)) + #Use the indicator markers for player for the first argument after ggplot( and also after the x = 
  geom_line() +
  geom_point() +
  geom_line(aes(y = KI$RegSeasonAPG),color = "blue")+
  geom_smooth(method = "lm", se = FALSE, color = "red")+
  labs(title = "Pts for Desired Player", #Here you would insert the players name as well after "for" and the respective stat line you modeled
       x = "Game",
       y = "Points")
```

```{r echo = T}
#Confidence interval for desired player and the stat line wished upon

t.test(MC$Reb, conf.level = 0.30)$conf.int
```

```{r echo = T}
#Finding the percentage of how many times a player has done this kind of stat line in the playoffs

# Calculate bet proportions and store in a named list
bets <- list(
  bet1 = sum(LD$Pts >= 20) / nrow(LD),
  bet2 = sum(DG$Pts < 10.5) / nrow(DG),
  bet3 = sum(DL$Pts < 10.5) / nrow(DL),
  bet4 = sum(DL$Pts > 6.5) / nrow(DL),
  bet5 = sum(MC$Pts > 10.5) / nrow(MC),
  bet6 = sum(MC$Reb > 1.5) / nrow(MC),
  bet7 = sum(KT$`3PM` < 2.5) / nrow(KT),
  bet8 = sum(MC$`3PM` < 2.5) / nrow(MC),
  bet9 = sum(PJ$`3PM` < 2.5) / nrow(PJ),
  bet10 = sum(DL$Reb >= 5) / nrow(DL),
  bet11 = sum(DG$Reb >= 5) / nrow(DG),
  bet12 = sum(AE$Reb >= 5) / nrow(AE),
  bet13 = sum(KT$Reb >= 5) / nrow(KT),
  bet14 = sum(LD$Reb >= 8) / nrow(LD),
  bet15 = sum(RG$Reb > 8) / nrow(RG),
  bet16 = sum(AE$Assists >= 5) / nrow(LD),
  bet17 = sum(MC$Assists >= 5) / nrow(MC),
  bet18 = sum(KI$Assists < 6.5) / nrow(KI),
  bet19 = sum(JM$Reb > 1.5) / nrow(JM),
  bet20 = sum(KI$Reb > 1.5) / nrow(KI),
  bet21 = sum(KI$Reb < 5.5) / nrow(KI),
  bet22 = sum(LD$Reb < 10.5) / nrow(LD),
  bet23 = sum(JG$`3PM` > 0.5) / nrow(JG),
  bet24 = sum(JM$Pts < 12.5) / nrow(JM),
  bet25 = sum(JM$Pts >= 8) / nrow(JM),
  bet26 = sum(LD$Pts >= 25) / nrow(LD)
)

threshold <- 0.8

good_bets <- bets[sapply(bets, function(x) x >= threshold)]

good_bets
```


```{r echo = T}
#Percentage change of hitting bet (Take all percentages above and add it to the numbers )

parlay_percent <- (bets$bet1 * bets$bet6 * bets$bet12 * bets$bet13 * bets$bet16 *bets$bet18 *bets$bet19 *bets$bet20)
parlay_percent
```

```{r echo = T}
#Calculate odds for the total parlay based on number of legs that you have

parlay_odds <- function(bet_size, ...) {
  odds_vals <- list(...)
  n_odds <- length(odds_vals)
  dec_odds <- numeric(n_odds)
  
#Conversions
  for (i in seq_along(odds_vals)) {
    if (odds_vals[[i]] < 0) {
      dec_odds[i] <- (abs(odds_vals[[i]]) + 100) / abs(odds_vals[[i]])
    } else {
      dec_odds[i] <- 1 + (odds_vals[[i]] / 100)
    }
  }
  
#Total odds for parlay
  tot_dec_odds <- prod(dec_odds)
  
#Payout to Bettor
  potential_payout <- (bet_size * tot_dec_odds)
  profit <- potential_payout - bet_size
  
  return(list(total_decimal_odds = tot_dec_odds, potential_payout = potential_payout ,profit=profit))
}

#This is where you would put in your data. Bet size is your bet size. The numbers afterwards are DraftKings calculations for how much you would win. Therefore, there will be no need for odds input above.

bet_size <- 10

#Right here is where you put all odds below after bet_size.
result <- parlay_odds(bet_size, 100)

total_decimal_odds <- result$total_decimal_odds
potential_payout <- result$potential_payout
profit <- result$profit

#Here are the outputs. First number will be the total odds of a bet. The second number will be how much the payout will be in total if you were to win.
print(total_decimal_odds)
print(potential_payout)
print(profit)
```


